// GET /expenses (limit & offset)
export const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST'
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS'
export const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE'

// POST /expenses/:id
export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE'

// POST /expenses/:id/receipts
export const ADD_RECEIPT_REQUEST = 'ADD_RECEIPT_REQUEST'
export const ADD_RECEIPT_SUCCESS = 'ADD_RECEIPT_SUCCESS'
export const ADD_RECEIPT_FAILURE = 'ADD_RECEIPT_FAILURE'
